name: Build and publish Docker image bro-fixe-web

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: rauchmat/bro-fixe-web
            dockerfile: src/Web/Dockerfile
          - image: rauchmat/bro-fixe-db
            dockerfile: src/Database/Dockerfile
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ matrix.image }}
        tags: |
          type=semver,pattern={{version}}
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: src
        file: ${{ matrix.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
