name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: List file contents
      run: |
        ls ${{ github.workspace }}
      
    - name: Build the Web Docker image
      run: docker build ./src/ --file src/Web/Dockerfile --tag bro-fixe/web:$(date +%s)
